export const GET_WEATHER_REQUESTED = 'GET_WEATHER_REQUESTED';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED';

export const GET_SEARCH_WEATHER_REQUESTED = 'GET_SEARCH_WEATHER_REQUESTED';
export const GET_SEARCH_WEATHER_SUCCESS = 'GET_SEARCH_WEATHER_SUCCESS';
export const GET_SEARCH_WEATHER_FAILED = 'GET_SEARCH_WEATHER_FAILED';
